[package]
name = "project-euler"
version = "0.1.0"
authors = ["Eclésio Júnior <eclesiomelo.1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
